// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsJzdVHo4I1Urb9Cjbe1OaQuNBMmMh5II',
    appId: '1:517026597072:web:18dda94795636a576d36d5',
    messagingSenderId: '517026597072',
    projectId: 'tugende-14fee',
    authDomain: 'tugende-14fee.firebaseapp.com',
    storageBucket: 'tugende-14fee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB0aTeYLeHsj3mBY4G6brpbq7ZvZq6MB4',
    appId: '1:517026597072:android:253ab24372d18bab6d36d5',
    messagingSenderId: '517026597072',
    projectId: 'tugende-14fee',
    storageBucket: 'tugende-14fee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEseXW0Q46yy1c4Qcpz5Pkhixi03PatoE',
    appId: '1:517026597072:ios:83111903c86825da6d36d5',
    messagingSenderId: '517026597072',
    projectId: 'tugende-14fee',
    storageBucket: 'tugende-14fee.firebasestorage.app',
    iosClientId: '517026597072-9uhsl4pms5afchq28d88a1ieemknfp12.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugende',
  );
}
